In [1]:
import pandas as pd

In [47]:
df=pd.read_csv("./data.csv")

In [18]:
def greetings(name):
    print("Good Day " + name)

In [22]:
greetings("james")

Good Day james

In [50]:
df.columns

Index(['age', 'gender', 'review', 'education', 'purchased'], dtype='object')

In [51]:
df['gender']=df['gender'].str.replace("Female","Lady")

In [64]:
def change(x):
    x.pandas.Series.str.replace("No","Better luck")

In [65]:
df['purchased']=df['purchased'].apply(change)

AttributeError: 'str' object has no attribute 'pandas'

In [58]:
df

    age gender   review education purchased
0    30   None  Average    School        No
1    68   None     Poor        UG        No
2    70   None     Good        PG        No
3    72   None     Good        PG        No
4    16   None  Average        UG        No
5    31   None  Average    School       Yes
6    18   None     Good    School        No
7    60   None     Poor    School       Yes
8    65   None  Average        UG        No
9    74   None     Good        UG       Yes
10   98   None     Good        UG       Yes
11   74   None     Good        UG       Yes
12   51   None     Poor    School        No
13   57   None  Average    School        No
14   15   None     Poor        PG       Yes
15   75   None     Poor        UG        No
16   59   None     Poor        UG       Yes
17   22   None     Poor        UG       Yes
18   19   None     Good    School        No
19   97   None     Poor        PG       Yes
20   57   None  Average    School       Yes
21   32   None  Average        PG        No
22   18   None     Poor        PG       Yes
23   96   None     Good    School        No
24   16   None  Average        PG       Yes
25   57   None     Good    School        No
26   53   None     Poor        PG        No
27   69   None     Poor        PG        No
28   48   None     Poor    School        No
29   83   None  Average        UG       Yes
30   73   None  Average        UG        No
31   22   None     Poor    School       Yes
32   92   None  Average        UG       Yes
33   89   None     Good        PG       Yes
34   86   None  Average    School        No
35   74   None     Poor    School       Yes
36   34   None     Good        UG       Yes
37   94   None  Average        PG       Yes
38   45   None     Good    School        No
39   76   None     Poor        PG        No
40   39   None     Good    School        No
41   23   None     Good        PG       Yes
42   30   None     Good        PG       Yes
43   27   None     Poor        PG        No
44   77   None  Average        UG        No
45   61   None     Poor        PG       Yes
46   64   None     Poor        PG        No
47   38   None     Good        PG       Yes
48   39   None     Good        UG       Yes
49   25   None     Good        UG        No